[package]
name = "darwinia-phragmen"
version = "0.5.0"
authors = ["Darwinia Network <hello@darwinia.network>"]
edition = "2018"
license = "GPL-3.0"
homepage = "https://darwinia.network/"
repository = "https://github.com/darwinia-network/darwinia/"
description = "PHRAGMENT primitives"

[dependencies]
# crates.io
serde = { version = "1.0.101", optional = true, features = ["derive"] }

# github.com
sp-std = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.3" }
sp-runtime = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.3" }

# darwinia
darwinia-support = { default-features = false, path = "../../frame/support" }

[dev-dependencies]
rand = "0.7.2"

sp-io ={ git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.3" }
substrate-test-utils = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.3" }

[features]
default = ["std"]
std = [
	"serde",

	"sp-std/std",
	"sp-runtime/std",

	"darwinia-support/std",
]
