[package]
name = "node-primitives"
version = "0.5.0"
authors = ["Darwinia Network <hello@darwinia.network>"]
edition = "2018"
license = "GPL-3.0"
homepage = "https://darwinia.network/"
repository = "https://github.com/darwinia-network/darwinia/"
description = "Darwinia node primitives"

[dependencies]
sp-core = { version = "2.0.0", default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
sp-runtime = { version = "2.0.0", default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }

[dev-dependencies]
pretty_assertions = "0.6.1"

sp-serializer = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.3" }

[features]
default = ["std"]
std = [
	"sp-core/std",
	"sp-runtime/std",
]
