[package]
name = "node-primitives"
version = "0.4.0"
authors = ["darwinia <hello@darwinia.network>"]
edition = "2018"

[dependencies]
sp-core = { version = "2.0.0", default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
sp-runtime = { version = "2.0.0", default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }

[features]
default = ["std"]
std = [
	"sp-core/std",
	"sp-runtime/std",
]
