[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia node runtime primitives"
edition     = "2018"
homepage    = "https://darwinia.network/"
license     = "GPL-3.0"
name        = "darwinia-primitives"
repository  = "https://github.com/darwinia-network/darwinia/"
version     = "0.11.2"

[dependencies]
# crates.io
codec = { package = "parity-scale-codec", version = "2.1.1", default-features = false }
# paritytech frame
frame-system = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
# paritytech primitives
sp-application-crypto = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
sp-core               = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
sp-runtime            = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }

[dev-dependencies]
frame-support = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }


[features]
default = ["std"]

std = [
	# crates.io
	"codec/std",
	# paritytech frame
	"frame-system/std",
	# paritytech primitives
	"sp-application-crypto/std",
	"sp-core/std",
	"sp-runtime/std",
]
