[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia node runtime primitives"
edition     = "2018"
homepage    = "https://darwinia.network/"
license     = "GPL-3.0"
name        = "darwinia-primitives"
repository  = "https://github.com/darwinia-network/darwinia/"
version     = "0.8.9"

[dependencies]
# crates
codec = { package = "parity-scale-codec", version = "1.3.5", default-features = false }
# substrate frame
frame-system = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
# substrate primitives
sp-application-crypto = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
sp-core               = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
sp-runtime            = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }

[features]
default = ["std"]

std = [
	"crates-std",
	"substrate-frame-std",
	"substrate-primitives-std",
]

crates-std               = ["codec/std"]
substrate-frame-std      = ["frame-system/std"]
substrate-primitives-std = [
	"sp-application-crypto/std",
	"sp-core/std",
	"sp-runtime/std",
]
