[package]
name = "darwinia-primitives"
version = "0.6.4"
authors = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia node runtime primitives"
edition = "2018"
license = "GPL-3.0"
homepage = "https://darwinia.network/"
repository = "https://github.com/darwinia-network/darwinia/"

[dependencies]
# crates
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false }
# substrate primitives
sp-application-crypto = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-rc.darwinia.3" }
sp-core = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-rc.darwinia.3" }
sp-runtime = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-rc.darwinia.3" }
# substrate frame
frame-system = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-rc.darwinia.3" }

[features]
default = ["std"]
std = [
	# crates
	"codec/std",
	# substrate primitives
	"sp-application-crypto/std",
	"sp-core/std",
	"sp-runtime/std",
	# substrate frame
	"frame-system/std",
]
