language: rust
rust:
  - nightly

branches:
    only:
        - master
        - develop

env:
    global:
        - RUST_BACKTRACE=1

before_install:
    # Check how much space we've got on this machine.
    - df -h
    - rustup target add wasm32-unknown-unknown

jobs:
  include:
    - stage: Check & Prepare
      script: .maintain/ci/fmt_script.sh

    - stage: Build
      env: RUST_TOOLCHAIN=nightly TARGET=native
      script: .maintain/ci/build_script.sh

    - stage: Build
      env: RUST_TOOLCHAIN=nightly TARGET=wasm
      script: .maintain/ci/build_script.sh

    - stage: Darwinia Test
      env: RUST_TOOLCHAIN=nightly TARGET=native KTON
      script: .maintain/ci/darwinia_test_script.sh kton

    - stage: Darwinia Test
      env: RUST_TOOLCHAIN=nightly TARGET=native RING
      script: .maintain/ci/darwinia_test_script.sh ring

    - stage: Darwinia Test
      env: RUST_TOOLCHAIN=nightly TARGET=native STAKING
      script: .maintain/ci/darwinia_test_script.sh staking

    - stage: Overall Test 
      env: RUST_TOOLCHAIN=nightly TARGET=native
      script: .maintain/ci/test_script.sh

after_script:
    # Check how much free disk space left after the build
    - df -h
