language: rust
rust: nightly

branches:
  only:
    - master

env:
  global:
    - RUST_BACKTRACE=1

before_install:
  - df -h
  - rustup target add wasm32-unknown-unknown --toolchain nightly

jobs:
  include:
    - stage: Check & Prepare
      script: .maintain/ci/format.sh

    - stage: Build
      env: RUST_TOOLCHAIN=nightly
      script: .maintain/ci/build.sh

after_script:
  - df -h
