
# Request an environment that provides sudo (that goes with larger containers)
# and a minimal language environment.
language: shell

cache: cargo

branches:
    only:
        - master
        - develop

env:
    global:
        - RUST_BACKTRACE=1

before_install:
    # Check how much space we've got on this machine.
    - df -h

jobs:
  include:
    - stage: Fomat Check
      env: RUST_TOOLCHAIN=stable TARGET=native
      script: .maintain/ci/fmt_script.sh

    - stage: Build Native
      env: RUST_TOOLCHAIN=nightly TARGET=native
      script: .maintain/ci/build_script.sh

    - stage: Build Wasm
      env: RUST_TOOLCHAIN=nightly TARGET=wasm
      script: .maintain/ci/build_script.sh

    - stage: Test Kton
      env: RUST_TOOLCHAIN=nightly TARGET=native
      script: .maintain/ci/darwinia_test_script.sh kton

    - stage: Test Ring
      env: RUST_TOOLCHAIN=nightly TARGET=native
      script: .maintain/ci/darwinia_test_script.sh ring

    - stage: Test Staking
      env: RUST_TOOLCHAIN=nightly TARGET=native
      script: .maintain/ci/darwinia_test_script.sh staking

    - stage: Test Everything
      env: RUST_TOOLCHAIN=nightly TARGET=native
      script: .maintain/ci/test_script.sh

after_script:
    # Check how much free disk space left after the build
    - df -h
