[profile.release]
panic = 'unwind'

[workspace]
members = [
	"core/cli",
    "core/merkle-mountain-range",
    "core/fly-client",
    "core/sr-eth-primitives",
    "core/merkle-patricia-trie",

	"node/cli",
    "node/executor",
    "node/primitives",
    "node/rpc",
    "node/rpc-client",
    "node/runtime",

    "srml/balances",
    "srml/ethereum-bridge",
    "srml/kton",
    "srml/staking",
    "srml/support"
]
