[workspace]
members = [
	"bin/node/cli",
	"bin/node/executor",
	"bin/node/rpc",
	"bin/node/runtime",
# TODO benchmarking
#	"bin/node/testing",
]

[profile.release]
# Darwinia runtime requires unwinding.
panic = "unwind"
