[[bin]]
name = "darwinia"
path = "src/main.rs"

[package]
name = "darwinia"
version = "0.6.3"
authors = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia node implementation in Rust"
edition = "2018"
license = "GPL-3.0"
homepage = "https://darwinia.network/"
repository = "https://github.com/darwinia-network/darwinia/"

[dependencies]
# crates
futures = { version = "0.3.4" }
parity-util-mem = { version = "*", default-features = false, features = ["jemalloc-global"] }
# darwinia
darwinia-cli = { path = "cli" }
darwinia-service = { path = "service" }

[dev-dependencies]
assert_cmd = { version = "1.0.1" }
nix = { version = "0.17" }
tempfile = { version = "3.1.0" }

[workspace]
members = [
	"cli",
	"primitives",
	"rpc",
	"runtime/common",
	"runtime/crab",
	"service",
]
exclude = []

[badges]
maintenance = { status = "actively-developed" }

[profile.release]
# Darwinia runtime requires unwinding.
panic = "unwind"

[features]
# TODO: benchmark
# runtime-benchmarks=["darwinia-cli/runtime-benchmarks"]
