[workspace]
members = [
	"bin/node/cli",
	"bin/node/runtime",
	"frame/balances/kton",
	"frame/balances/ring",
	"frame/staking",
	"frame/support",
]

[profile.release]
# Substrate runtime requires unwinding.
panic = "unwind"
