[workspace]
members = [
	"bin/node/cli",
	"bin/node/executor",
	"bin/node/rpc",
	"bin/node/runtime",
# TODO benchmarking
#	"bin/node/testing",
	"frame/balances/kton",
	"frame/balances/ring",
	"frame/claims",
	"frame/chainrelay/eth/backing",
	"frame/chainrelay/eth/relay",
	"frame/elections-phragmen",
	"frame/staking",
	"frame/support",
	"frame/treasury",
	"frame/vesting",
	"primitives/ethash",
	"primitives/eth-primitives",
	"primitives/merkle-patricia-trie",
	"primitives/phragmen",
]

[profile.release]
# Darwinia runtime requires unwinding.
panic = "unwind"
