[workspace]
members = [
	"bin/node/cli",
	"bin/node/executor",
	"bin/node/inspect",
	"bin/node/primitives",
	"bin/node/rpc-client",
	"bin/node/rpc",
	"bin/node/runtime",
# TODO benchmarking
#	"bin/node/testing",
	"bin/node/transaction-factory",
	"client/cli",
	"frame/authority-discovery",
	"frame/babe",
	"frame/balances/kton",
	"frame/balances/ring",
	"frame/claims",
	"frame/chainrelay/eth/backing",
	"frame/chainrelay/eth/relay",
	"frame/elections-phragmen",
	"frame/grandpa",
	"frame/im-online",
	"frame/offences",
	"frame/session",
	"frame/staking",
	"frame/support",
	"frame/treasury",
	"frame/vesting",
	"primitives/ethash",
	"primitives/eth-primitives",
	"primitives/merkle-patricia-trie",
	"primitives/phragmen",
	"primitives/staking",
]

[profile.release]
# Darwinia runtime requires unwinding.
panic = "unwind"
