[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia node implementation in Rust"
edition     = "2018"
homepage    = "https://darwinia.network/"
license     = "GPL-3.0"
name        = "darwinia"
repository  = "https://github.com/darwinia-network/darwinia/"
version     = "0.9.5"

[[bin]]
name = "darwinia"
path = "src/main.rs"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
# crates
futures         = { version = "=0.3.8" }
parity-util-mem = { version = "*", default-features = false, features = ["jemalloc-global"] }
# darwinia
darwinia-cli     = { path = "cli" }
darwinia-service = { path = "node/service" }

[features]
default = ["darwinia-cli/wasmtime"]
dev     = [
	"darwinia-service/dev",
	"darwinia-cli/dev",
]

[workspace]
members = [
	"cli",
	"primitives",
	"rpc",
	"runtime/common",
	"runtime/crab",
	"runtime/darwinia",
	"node/service",
]

[profile.release]
# Darwinia runtime requires unwinding.
panic = "unwind"

[patch."https://github.com/darwinia-network/rust-ethash.git"]
ethash = { git = "https://github.com/darwinia-network/ethash.git", tag = "v1.0.0" }
