[workspace]
members = [
	"bin/node/cli",
	"bin/node/executor",
	"bin/node/primitives",
	"bin/node/rpc-client",
	"bin/node/rpc",
	"bin/node/runtime",
	"frame/balances/kton",
	"frame/balances/ring",
	"frame/chainrelay/eth/backing",
	"frame/chainrelay/eth/relay",
	"frame/staking",
	"frame/support",
	"frame/treasury",
	"primitives/ethash",
	"primitives/merkle-patricia-trie",
	"primitives/phragmen",
	"primitives/sp-eth-primitives",
]

[profile.release]
# Substrate runtime requires unwinding.
panic = "unwind"
