[dependencies]
cli = { package = "node-cli", path = "node/cli" }
futures = "0.1.29"
ctrlc = { version = "3.1.3", features = ["termination"] }
substrate-cli = { git = 'https://github.com/darwinia-network/substrate.git' }
substrate-client = { git = 'https://github.com/darwinia-network/substrate.git' }
substrate-client-db = { git = 'https://github.com/darwinia-network/substrate.git' }
substrate-consensus-aura = { git = 'https://github.com/darwinia-network/substrate.git' }
substrate-consensus-babe = { git = 'https://github.com/darwinia-network/substrate.git' }
substrate-consensus-common = { git = 'https://github.com/darwinia-network/substrate.git' }
substrate-consensus-rhd = { git = 'https://github.com/darwinia-network/substrate.git' }
substrate-consensus-slots = { git = 'https://github.com/darwinia-network/substrate.git' }
substrate-executor = { git = 'https://github.com/darwinia-network/substrate.git' }
substrate-finality-grandpa = { git = 'https://github.com/darwinia-network/substrate.git' }
substrate-finality-grandpa-primitives = { git = 'https://github.com/darwinia-network/substrate.git' }
substrate-inherents = { git = 'https://github.com/darwinia-network/substrate.git' }
substrate-keyring = { git = 'https://github.com/darwinia-network/substrate.git' }
substrate-keystore = { git = 'https://github.com/darwinia-network/substrate.git' }
substrate-network = { git = 'https://github.com/darwinia-network/substrate.git' }
substrate-panic-handler = { git = 'https://github.com/darwinia-network/substrate.git' }
substrate-primitives = { git = 'https://github.com/darwinia-network/substrate.git' }
substrate-rpc = { git = 'https://github.com/darwinia-network/substrate.git' }
substrate-rpc-servers = { git = 'https://github.com/darwinia-network/substrate.git' }
substrate-serializer = { git = 'https://github.com/darwinia-network/substrate.git' }
substrate-service = { git = 'https://github.com/darwinia-network/substrate.git' }
substrate-service-test = { git = 'https://github.com/darwinia-network/substrate.git' }
sr-api = { git = 'https://github.com/darwinia-network/substrate.git' }
sr-api-proc-macro = { git = 'https://github.com/darwinia-network/substrate.git' }
sr-io = { git = 'https://github.com/darwinia-network/substrate.git' }
sr-primitives = { git = 'https://github.com/darwinia-network/substrate.git' }
sr-sandbox = { git = 'https://github.com/darwinia-network/substrate.git' }
sr-std = { git = 'https://github.com/darwinia-network/substrate.git' }
sr-version = { git = 'https://github.com/darwinia-network/substrate.git' }
substrate-state-machine = { git = 'https://github.com/darwinia-network/substrate.git' }
substrate-telemetry = { git = 'https://github.com/darwinia-network/substrate.git' }
substrate-transaction-pool = { git = 'https://github.com/darwinia-network/substrate.git' }
substrate-transaction-graph = { git = 'https://github.com/darwinia-network/substrate.git' }
substrate-trie = { git = 'https://github.com/darwinia-network/substrate.git' }
fork-tree = { git = 'https://github.com/darwinia-network/substrate.git' }
#new
substrate-application-crypto = { git = 'https://github.com/darwinia-network/substrate.git' }
substrate-authority-discovery = { git = 'https://github.com/darwinia-network/substrate.git' }
substrate-basic-authorship = { git = 'https://github.com/darwinia-network/substrate.git' }
substrate-externalities = { git = 'https://github.com/darwinia-network/substrate.git' }
substrate-offchain = { git = 'https://github.com/darwinia-network/substrate.git' }
substrate-peerset = { git = 'https://github.com/darwinia-network/substrate.git' }
substrate-phragmen = { git = 'https://github.com/darwinia-network/substrate.git' }
substrate-session = { git = 'https://github.com/darwinia-network/substrate.git' }
substrate-wasm-interface = { git = 'https://github.com/darwinia-network/substrate.git' }

[build-dependencies]
vergen = "3.0.4"

[profile.release]
panic = 'unwind'

[[bin]]
name = 'darwinia'
path = 'node/src/main.rs'

[workspace]
members = [
    "core/merkle-mountain-range",
    "core/fly-client",
    "core/sr-eth-primitives",
    "core/sr-rlp",

#    "darwinia-client",

	"node/cli",
    "node/executor",
    "node/primitives",
    "node/runtime",
    "node/rpc-client",

    "srml/support",
	"srml/try",

	"srml/chainrelay/bridge/eos",
	"srml/chainrelay/bridge/ethereum",

    "srml/kton",
    "srml/staking",
]

exclude = ["node/runtime/wasm"]

[package]
authors = ['Darwinia Network <hello@darwinia.network>']
build = 'build.rs'
edition = '2018'
name = 'darwinia'
version = '0.3.2'
