[package]
name = "land-chain"
version = "0.2.0"
authors = ["Evolution Land <hello@evolution.land>"]
build = "build.rs"

[[bin]]
name = "land-chain"
path = "node/src/main.rs"

[dependencies]
error-chain = "0.12"
evo-cli = { path = "node/cli" }
futures = "0.1"
ctrlc = { version = "3.0", features = ["termination"] }

[build-dependencies]
vergen = "3"

[workspace]
members = [
	"node/runtime",
	"node/cli",
	"node/executor",
	"node/primitives",
	"node/service",
	"srml/sdr",
	"srml/token/ring",
	"srml/token/kton",
]
exclude = [ "node/runtime/wasm" ]

[badges]
travis-ci = { repository = "paritytech/substrate", branch = "master" }
maintenance = { status = "actively-developed" }
is-it-maintained-issue-resolution = { repository = "paritytech/substrate" }
is-it-maintained-open-issues = { repository = "paritytech/substrate" }

[profile.release]
# Substrate runtime requires unwinding.
panic = "unwind"