[workspace]
members = [
	"bin/node/cli",
	"bin/node/executor",
	"bin/node/primitives",
	"bin/node/rpc-client",
	"bin/node/rpc",
	"bin/node/runtime",
	"frame/balances/kton",
	"frame/balances/ring",
	"frame/staking",
	"frame/support",
	"frame/treasury",
	"primitives/phragmen",
]

[profile.release]
# Substrate runtime requires unwinding.
panic = "unwind"
