[profile.release]
panic = 'unwind'

[workspace]
members = [
    "core/merkle-mountain-range",
    "core/fly-client",
    "core/sr-eth-primitives",

	"node/cli",
    "node/executor",
    "node/primitives",
    "node/rpc",
    "node/rpc-client",
    "node/runtime",

    "srml/support",
    "srml/balances",
    "srml/kton",
    "srml/staking",
    "srml/ethereum-bridge"
]
