[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia node implementation in Rust"
edition     = "2018"
homepage    = "https://darwinia.network/"
license     = "GPL-3.0"
name        = "darwinia"
repository  = "https://github.com/darwinia-network/darwinia/"
version     = "0.11.4"

[[bin]]
name = "darwinia"
path = "src/main.rs"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
# crates.io
futures         = { version = "0.3.15" }
parity-util-mem = { version = "0.9.0", default-features = false, features = ["jemalloc-global"] }
# darwinia-network
darwinia-cli     = { path = "cli" }
darwinia-service = { path = "node/service" }

[features]
default = ["darwinia-cli/wasmtime"]

dev = [
	"darwinia-service/dev",
	"darwinia-cli/dev",
]

try-runtime = ["darwinia-cli/try-runtime"]

runtime-benchmarks = ["darwinia-cli/runtime-benchmarks"]

[workspace]
members = [
	"cli",
	"primitives",
	"rpc",
	"runtime/common",
	"runtime/crab",
	"runtime/darwinia",
	"node/service",
]

[profile.release]
# Darwinia runtime requires unwinding.
panic = "unwind"
