[package]
name = "node-primitives"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
primitives = { package = "substrate-primitives", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
sr-primitives = { package = "sr-primitives", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }

[dev-dependencies]
substrate-serializer = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
pretty_assertions = "0.6.1"

[features]
default = ["std"]
std = [
	"primitives/std",
	"sr-primitives/std",
]
