[package]
name = "evo-primitives"
version = "0.1.0"
authors = ["Evolution Land <hello@evolution.land>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }
parity-codec = { version = "3.3", default-features = false, features = ["derive"] }
substrate-primitives = { git = "https://github.com/paritytech/substrate", default-features = false }
rstd = { package = "sr-std", git = "https://github.com/paritytech/substrate", default-features = false }
runtime_primitives = { package = "sr-primitives", git = "https://github.com/paritytech/substrate", default-features = false }

[dev-dependencies]
substrate-serializer = { git = "https://github.com/paritytech/substrate" }
pretty_assertions = "0.5"

[features]
default = ["std"]
std = [
	"parity-codec/std",
	"substrate-primitives/std",
	"rstd/std",
	"runtime_primitives/std",
	"serde_derive",
	"serde",
]
