[package]
name = "evo-runtime-wasm"
version = "0.1.0"
<<<<<<< HEAD
authors = ["Evolution Land <hello@evolution.land>"]
=======
authors = ["Commonwealth Labs <hello@commonwealth.im>"]
>>>>>>> upstream/master

[lib]
name = "evo_runtime"
crate-type = ["cdylib"]

[dependencies]
evo-runtime = { path = "..", default-features = false }

[features]
default = []
std = [
	"evo-runtime/std",
]

[profile.release]
panic = "abort"
lto = true

[workspace]
members = []