[package]
name = "evo-staking"
version = "0.1.0"
authors = ["hammeWang <dsw0602@foxmail.com>"]
edition = "2018"

[dependencies]
hex-literal = "0.1.0"
serde = { version = "1.0", default-features = false }
serde_derive = { version = "1.0", optional = true }
safe-mix = { version = "1.0", default-features = false}
parity-codec = { version = "3.0", default-features = false }
parity-codec-derive = { version = "3.0", default-features = false }
substrate-keyring = { git = "https://github.com/paritytech/substrate", optional = true }
substrate-primitives = { git = "https://github.com/paritytech/substrate", default-features = false }
rstd = { package ="sr-std",  git = "https://github.com/paritytech/substrate", default-features = false }
primitives = { package ="sr-primitives",  git = "https://github.com/paritytech/substrate", default-features = false }
srml-support = { git = "https://github.com/paritytech/substrate", default-features = false }
system = { package ="srml-system",  git = "https://github.com/paritytech/substrate", default-features = false }
balances = { package ="srml-balances",  git = "https://github.com/paritytech/substrate", default_features = false }
timestamp = { package ="srml-timestamp",  git = "https://github.com/paritytech/substrate", default_features = false }
evo-support = {path = "../support", default_features = false}
runtime_io = { package = "sr-io", git = "https://github.com/paritytech/substrate", default-features = false }
session = { package ="srml-session", git = "https://github.com/paritytech/substrate", default-features = false }
consensus = { package ="srml-consensus", git = "https://github.com/paritytech/substrate", default-features = false }

[dev-dependencies]
ring = { package = "evo-ring", path = "../token/ring"}
kton = { package = "evo-kton", path = "../token/kton"}

[features]
default = ["std"]
std = [
    "serde/std",
    "serde_derive",
    "safe-mix/std",
    "parity-codec/std",
    "parity-codec-derive/std",
    "substrate-primitives/std",
    "rstd/std",
    "srml-support/std",
    "balances/std",
    "primitives/std",
    "system/std",
    "timestamp/std",
    "session/std",
    "consensus/std",
]
