[package]
name = "darwinia-staking"
version = "0.3.0"
authors = ["darwinia <hello@darwinia.network>"]
edition = "2018"

[dependencies]
# crates.io
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
regex = { version = "1.3.1", optional = true }
serde = { version = "1.0.101", optional = true }

# github.com
authorship = { package = "srml-authorship", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
phragmen = { package = "substrate-phragmen", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
rstd = { package = "sr-std", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
session = { package = "srml-session",git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false, features = ["historical"] }
srml-support = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
sr-primitives = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
sr-staking-primitives = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
substrate-primitives = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
system = { package = "srml-system", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
timestamp = { package = "srml-timestamp", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }

# darwinia
darwinia-support = { package = "darwinia-support", path = "../support", default-features = false }

[dev-dependencies]
runtime-io = { package = "sr-io", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }

balances = { package = "darwinia-balances", path = '../balances' }
kton = { package = "darwinia-kton", path = "../kton" }

[features]
equalize = []
default = ["std", "equalize"]
std = [
	"codec/std",
	"regex/std",
	"serde",

	"authorship/std",
	"phragmen/std",
	"rstd/std",
	"session/std",
	"srml-support/std",
	"sr-primitives/std",
    "sr-staking-primitives/std",
	"substrate-primitives/std",
	"system/std",
	"timestamp/std",

	"darwinia-support/std",
]
