[package]
name = "node-runtime"
version = "0.2.0"
authors = ["Darwinia Network <hello@darwinia.network>"]
edition = "2018"

[dependencies]
# crates.io
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
integer-sqrt = { version = "0.1.2" }
rustc-hex = { version = "2.0", optional = true }
safe-mix = { version = "1.0", default-features = false }
serde = { version = "1.0.101", optional = true }

# github.com
authorship = { package = "srml-authorship", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
authority-discovery-primitives = { package = "substrate-authority-discovery-primitives", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false } # staking tests needed
authority-discovery = { package = "srml-authority-discovery", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
babe = { package = "srml-babe", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
babe-primitives = { package = "substrate-consensus-babe-primitives", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
block-builder-api = { package = "substrate-block-builder-runtime-api", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
contracts = { package = "srml-contracts", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
contracts-rpc-runtime-api = { package = "srml-contracts-rpc-runtime-api", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
executive = { package = "srml-executive", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
finality-tracker = { package = "srml-finality-tracker", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
grandpa = { package = "srml-grandpa", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
im-online = { package = "srml-im-online", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
indices = { package = "srml-indices", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
inherents = { package = "substrate-inherents", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
offchain-primitives = { package = "substrate-offchain-primitives", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
offences = { package = "srml-offences", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
randomness-collective-flip = { package = "srml-randomness-collective-flip", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
rstd = { package = "sr-std", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
session = { package = "srml-session", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false, features = ["historical"] }
sr-api = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default_features = false }
sr-primitives = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
sr-staking-primitives = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
substrate-keyring = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", optional = true }
substrate-primitives = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
substrate-session = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
sudo = { package = "srml-sudo", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
support = { package = "srml-support", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
system = { package = "srml-system", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
system-rpc-runtime-api = { package = "srml-system-rpc-runtime-api", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
timestamp = { package = "srml-timestamp", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
transaction-payment = { package = "srml-transaction-payment", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
transaction-payment-rpc-runtime-api = { package = "srml-transaction-payment-rpc-runtime-api", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
tx-pool-api = { package = "substrate-transaction-pool-runtime-api", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
utility = { package = "srml-utility", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
version = { package = "sr-version", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }

# darwinia
balances = { package = "darwinia-balances", path = '../../srml/balances', default-features = false }
eth-relay = { package = "darwinia-eth-relay", path = "../../srml/eth-relay", default-features = false }
kton = { package = "darwinia-kton", path = '../../srml/kton', default-features = false }
node-primitives = { path = "../primitives", default-features = false }
staking = { package = "darwinia-staking", path = "../../srml/staking", default-features = false }

[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", version = "1.0.2", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }

[features]
default = ["std"]
std = [
	# crates.io
	"codec/std",
	"rustc-hex",
	"safe-mix/std",
	"serde",

	# github.com
	"authorship/std",
	"authority-discovery/std",
	"authority-discovery-primitives/std",
	"babe/std",
	"babe-primitives/std",
	"block-builder-api/std",
	"contracts/std",
	"contracts-rpc-runtime-api/std",
	"executive/std",
	"finality-tracker/std",
	"grandpa/std",
	"im-online/std",
	"indices/std",
	"inherents/std",
	"offchain-primitives/std",
	"offences/std",
	"randomness-collective-flip/std",
	"rstd/std",
	"session/std",
	"sr-api/std",
	"sr-primitives/std",
	"sr-staking-primitives/std",
	"substrate-keyring",
	"substrate-primitives/std",
	"substrate-session/std",
	"sudo/std",
	"support/std",
	"system/std",
	"system-rpc-runtime-api/std",
	"timestamp/std",
	"transaction-payment/std",
	"transaction-payment-rpc-runtime-api/std",
	"tx-pool-api/std",
	"utility/std",
	"version/std",

	# darwinia
	"balances/std",
	"eth-relay/std",
	"kton/std",
	"node-primitives/std",
	"staking/std",
]
