[package]
name = "node-runtime"
version = "0.1.0"
authors = ["Darwinia Network <hello@itering.com>"]
edition = "2018"

[dependencies]
integer-sqrt = { version = "0.1.2" }
safe-mix = { version = "1.0", default-features = false }
rustc-hex = { version = "2.0", optional = true }
serde = { version = "1.0.101", optional = true }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }

substrate-primitives = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
sr-api = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default_features = false }
rstd = { package = "sr-std", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
sr-primitives = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
offchain-primitives = { package = "substrate-offchain-primitives", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
version = { package = "sr-version", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
support = { package = "srml-support", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
executive = { package = "srml-executive", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
finality-tracker = { package = "srml-finality-tracker", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
grandpa = { package = "srml-grandpa", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
indices = { package = "srml-indices", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
session = { package = "srml-session", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false, features = ["historical"] }
system = { package = "srml-system", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
timestamp = { package = "srml-timestamp", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
sudo = { package = "srml-sudo", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
node-primitives = {path = "../primitives", default-features = false }
consensus_aura = { package = "substrate-consensus-aura-primitives", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
substrate-keyring = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", optional = true }

# new
babe = { package = "srml-babe", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
babe-primitives = { package = "substrate-consensus-babe-primitives", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
system-rpc-runtime-api = { package = "srml-system-rpc-runtime-api", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
sr-staking-primitives = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
substrate-session = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
# staking tests needed
authority-discovery-primitives = { package = "substrate-authority-discovery-primitives", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }

# new and no-used
authority-discovery = { package = "srml-authority-discovery", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
authorship = { package = "srml-authorship", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
collective = { package = "srml-collective", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
contracts = { package = "srml-contracts", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
contracts-rpc-runtime-api = { package = "srml-contracts-rpc-runtime-api", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
democracy = { package = "srml-democracy", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
elections = { package = "srml-elections", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
im-online = { package = "srml-im-online", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
membership = { package = "srml-membership", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
offences = { package = "srml-offences", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
randomness-collective-flip = { package = "srml-randomness-collective-flip", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
treasury = { package = "srml-treasury", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
utility = { package = "srml-utility", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
transaction-payment = { package = "srml-transaction-payment", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
block-builder-api = { package = "substrate-block-builder-runtime-api", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
tx-pool-api = { package = "substrate-transaction-pool-runtime-api", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
inherents = { package = "substrate-inherents", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }

srml-staking-reward-curve = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }

transaction-payment-rpc-runtime-api = { package = "srml-transaction-payment-rpc-runtime-api", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }

darwinia-support = { path = "../../srml/support", default-features = false }
balances = { package = "darwinia-balances", path = '../../srml/balances', default-features = false }
kton = { package = "darwinia-kton", path = '../../srml/kton', default-features = false }
staking = { package = "darwinia-staking", path = "../../srml/staking", default-features = false }

merkle-mountain-range = { path = "../../core/merkle-mountain-range", default-features = false }

ethereum-bridge = { package = "darwinia-ethereum-bridge", path = "../../srml/chainrelay/bridge/ethereum", default-features = false }

[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", version = "1.0.2", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }

[features]
default = ["std"]
std = [
	"codec/std",
	"substrate-primitives/std",
	"rstd/std",
	"sr-primitives/std",
	"support/std",
	"balances/std",
	"contracts/std",
	"democracy/std",
	"executive/std",
	"finality-tracker/std",
	"grandpa/std",
	"indices/std",
	"session/std",
	"authorship/std",
	"system/std",
	"timestamp/std",
	"treasury/std",
	"sudo/std",
	"version/std",
	"node-primitives/std",
	"serde",
	"safe-mix/std",
	"sr-api/std",
	"consensus_aura/std",
	"rustc-hex",
	"substrate-keyring",
	"offchain-primitives/std",
	"babe-primitives/std",
	"system-rpc-runtime-api/std",
	"authority-discovery/std",
	"authority-discovery-primitives/std",
	"collective/std",
	"contracts-rpc-runtime-api/std",
	"elections/std",
	"im-online/std",
	"membership/std",
	"offences/std",
	"randomness-collective-flip/std",
	"utility/std",
	"transaction-payment/std",
	"transaction-payment-rpc-runtime-api/std",
	"sr-staking-primitives/std",
	"babe/std",
	"substrate-session/std",
	"block-builder-api/std",
    "tx-pool-api/std",
    "inherents/std",

    # custom module
    "darwinia-support/std",
	"kton/std",
	"staking/std",

    # chainrelay
    "ethereum-bridge/std",
]
