[package]
name = "darwinia-staking"
version = "0.4.0"
authors = ["Darwinia Network <hello@darwinia.network>"]
edition = "2018"

[dependencies]
# crates.io
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.101", optional = true }

# github.com
frame-support = { version = "2.0.0", default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
frame-system = { version = "2.0.0", default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
pallet-authorship = { version = "2.0.0", default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
pallet-session = { version = "2.0.0", default-features = false, features = ["historical"], git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
sp-core = { version = "2.0.0", default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
sp-io ={ default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
sp-keyring = { version = "2.0.0", optional = true, git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
sp-runtime = { version = "2.0.0", default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
sp-staking = { version = "2.0.0", default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
sp-std = { version = "2.0.0", default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }

# darwinia
darwinia-phragmen = { default-features = false, path = "../../primitives/phragmen" }
darwinia-support = {  default-features = false, path = "../support" }

[dev-dependencies]
substrate-test-utils = { version = "2.0.0", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
pallet-timestamp = { version = "2.0.0", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }

pallet-ring = { package = "darwinia-ring", path = "../../frame/balances/ring" }
pallet-kton = { package = "darwinia-kton", path = "../../frame/balances/kton" }

[features]
equalize = []
migrate = []
default = ["std", "equalize"]
std = [
	"codec/std",
	"serde",

	"frame-support/std",
	"frame-system/std",
	"pallet-authorship/std",
	"pallet-session/std",
	"sp-core/std",
	"sp-io/std",
	"sp-keyring",
	"sp-runtime/std",
	"sp-staking/std",
	"sp-std/std",

	"darwinia-phragmen/std",
	"darwinia-support/std",
]
