[package]
name = "node-rpc"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
client = { package = "substrate-client", git = 'https://github.com/paritytech/substrate.git' }
jsonrpc-core = "13.2.0"
node-primitives = { path = "../primitives" }
sr-primitives = { git = 'https://github.com/paritytech/substrate.git' }
srml-contracts-rpc = { git = 'https://github.com/paritytech/substrate.git' }
srml-system-rpc = { git = 'https://github.com/paritytech/substrate.git' }
transaction_pool = { package = "substrate-transaction-pool", git = 'https://github.com/paritytech/substrate.git' }
