[package]
name = "node-cli"
version = "0.5.0"
authors = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia node implementation in Rust."
build = "build.rs"
edition = "2018"
default-run = "darwinia"

[badges]
travis-ci = { repository = "darwinia-network/darwinia", branch = "develop" }
maintenance = { status = "actively-developed" }
is-it-maintained-issue-resolution = { repository = "darwinia-network/darwinia" }
is-it-maintained-open-issues = { repository = "darwinia-network/darwinia" }

[[bin]]
name = "darwinia"
path = "bin/main.rs"
required-features = ["cli"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# third-party dependencies
codec = { package = "parity-scale-codec", version = "1.0.6" }
futures = { version = "0.3.1", features = ["compat"] }
futures01 = { package = "futures", version = "0.1.29" }
hex-literal = "0.2.1"
jsonrpc-core = "14.0.3"
log = "0.4.8"
rand = "0.7.2"
serde = { version = "1.0.102", features = ["derive"] }
structopt = "=0.3.7"

# primitives
grandpa-primitives = { version = "2.0.0", package = "sp-finality-grandpa", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
sp-authority-discovery = { version = "2.0.0",  git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
sp-consensus = { version = "0.8", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
sp-consensus-babe = { version = "0.8", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
sp-core = { version = "2.0.0", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
sp-finality-tracker = { version = "2.0.0", default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
sp-inherents = { version = "2.0.0", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
sp-io = { version = "2.0.0", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
sp-keyring = { version = "2.0.0", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
sp-runtime = { version = "2.0.0", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
sp-timestamp = { version = "2.0.0", default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }

# client dependencies
grandpa = { version = "2.0.0", package = "sc-finality-grandpa", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
sc-authority-discovery = { version = "2.0.0",  git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
sc-basic-authority = { version = "2.0.0", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
sc-chain-spec = { version = "2.0.0", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
sc-client = { version = "2.0.0", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
sc-client-api = { version = "2.0.0", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
sc-client-db = { version = "2.0.0", default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
sc-consensus-babe = { version = "0.8", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
sc-network = { version = "0.8", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
sc-offchain = { version = "2.0.0", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
sc-rpc = { version = "2.0.0", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
sc-service = { version = "2.0.0", default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
sc-telemetry = { version = "2.0.0", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
sc-transaction-pool = { version = "2.0.0", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
sp-transaction-pool = { version = "2.0.0", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }

# frame dependencies
frame-support = { version = "2.0.0", default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
frame-system = { version = "2.0.0", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
pallet-authority-discovery = { version = "2.0.0",  git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
pallet-contracts = { version = "2.0.0", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
pallet-im-online = { version = "2.0.0", default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
pallet-indices = { version = "2.0.0", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
pallet-timestamp = { version = "2.0.0", default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
pallet-transaction-payment = { version = "2.0.0", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }

# node-specific dependencies
node-executor = { path = "../executor" }
node-primitives = { path = "../primitives" }
node-rpc = { path = "../rpc" }
node-runtime = { path = "../runtime" }

# CLI-specific dependencies
ctrlc = { version = "3.1.3", features = ["termination"], optional = true }
node-transaction-factory = { version = "2.0.0", optional = true, git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
tokio = { version = "0.1.22", optional = true }

sc-cli = { package = "darwinia-cli", optional = true, path = "../../../client/cli" }

# WASM-specific dependencies
clear_on_drop = { version = "0.2.3", features = ["no_cc"], optional = true }	# Imported just for the `no_cc` feature
console_error_panic_hook = { version = "0.1.1", optional = true }
console_log = { version = "0.1.2", optional = true }
js-sys = { version = "0.3.22", optional = true }
kvdb-memorydb = { version = "0.1.1", optional = true }
libp2p = { version = "0.13.0", default-features = false, optional = true }
rand6 = { package = "rand", version = "0.6", features = ["wasm-bindgen"], optional = true }	# Imported just for the `wasm-bindgen` feature
wasm-bindgen = { version = "0.2.45", optional = true }
wasm-bindgen-futures = { version = "0.3.22", optional = true }

[build-dependencies]
structopt = "=0.3.7"
vergen = "3.0.4"

build-script-utils = { version = "2.0.0", package = "substrate-build-script-utils", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }

sc-cli = { package = "darwinia-cli", path = "../../../client/cli" }

[features]
default = ["cli"]
browser = [
	"clear_on_drop",
	"console_error_panic_hook",
	"console_log",
	"js-sys",
	"kvdb-memorydb",
	"libp2p",
	"rand6",
    "rand/wasm-bindgen",
	"wasm-bindgen",
	"wasm-bindgen-futures",
]
cli = [
	"ctrlc",
	"node-executor/wasmi-errno",
	"node-transaction-factory",
	"sc-cli",
	"sc-service/rocksdb",
	"tokio",
]
wasmtime = [
	"cli",
	"node-executor/wasmtime",
	"sc-cli/wasmtime",
	"sc-service/wasmtime",
]
