[package]
name = "darwinia-chainrelay-poa"
version = "0.1.0"
authors = ["hammeWang <dsw0602@foxmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sr-primitives = {git = 'https://github.com/paritytech/substrate.git', default-features = false }
substrate-primitives = {git = 'https://github.com/paritytech/substrate.git', default-features = false }


[features]
default = ["std"]
std = [
    "sr-primitives/std",
    "substrate-primitives/std"
]