[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
build       = "build.rs"
description = "Darwinia node runtime for Darwinia network"
edition     = "2018"
homepage    = "https://darwinia.network/"
license     = "GPL-3.0"
name        = "darwinia-runtime"
repository  = "https://github.com/darwinia-network/darwinia/"
version     = "0.11.2"

[dependencies]
# crates.io
codec             = { package = "parity-scale-codec", version = "2.1.1", default-features = false, features = ["derive"] }
log               = { version = "0.4.14" }
serde             = { version = "1.0.126", optional = true }
serde_json        = { version = "1.0.64", optional = true }
smallvec          = { version = "1.6.1" }
static_assertions = { version = "1.1.0" }
# darwinia-network frame
darwinia-balances                   = { default-features = false, git = "https://github.com/darwinia-network/darwinia-common", branch = "master" }
darwinia-balances-rpc-runtime-api   = { default-features = false, git = "https://github.com/darwinia-network/darwinia-common", branch = "master" }
darwinia-crab-backing               = { default-features = false, git = "https://github.com/darwinia-network/darwinia-common", branch = "master" }
darwinia-democracy                  = { default-features = false, git = "https://github.com/darwinia-network/darwinia-common", branch = "master" }
darwinia-elections-phragmen         = { default-features = false, git = "https://github.com/darwinia-network/darwinia-common", branch = "master" }
darwinia-ethereum-backing           = { default-features = false, git = "https://github.com/darwinia-network/darwinia-common", branch = "master" }
darwinia-ethereum-relay             = { default-features = false, git = "https://github.com/darwinia-network/darwinia-common", branch = "master" }
darwinia-header-mmr                 = { default-features = false, git = "https://github.com/darwinia-network/darwinia-common", branch = "master" }
darwinia-header-mmr-rpc-runtime-api = { default-features = false, git = "https://github.com/darwinia-network/darwinia-common", branch = "master" }
darwinia-relay-authorities          = { default-features = false, git = "https://github.com/darwinia-network/darwinia-common", branch = "master" }
darwinia-relay-primitives           = { default-features = false, git = "https://github.com/darwinia-network/darwinia-common", branch = "master" }
darwinia-relayer-game               = { default-features = false, git = "https://github.com/darwinia-network/darwinia-common", branch = "master" }
darwinia-staking                    = { default-features = false, git = "https://github.com/darwinia-network/darwinia-common", branch = "master" }
darwinia-staking-rpc-runtime-api    = { default-features = false, git = "https://github.com/darwinia-network/darwinia-common", branch = "master" }
darwinia-support                    = { default-features = false, git = "https://github.com/darwinia-network/darwinia-common", branch = "master" }
darwinia-tron-backing               = { default-features = false, git = "https://github.com/darwinia-network/darwinia-common", branch = "master" }
darwinia-vesting                    = { default-features = false, git = "https://github.com/darwinia-network/darwinia-common", branch = "master" }
# darwinia-network primitives
darwinia-primitives = { default-features = false, path = "../../primitives" }
ethereum-primitives = { default-features = false, git = "https://github.com/darwinia-network/darwinia-common", branch = "master" }
# darwinia-network runtime
darwinia-runtime-common = { default-features = false, path = "../common" }
# paritytech frame
frame-benchmarking                         = { optional = true, default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
frame-executive                            = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
frame-support                              = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
frame-system                               = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
frame-system-benchmarking                  = { optional = true, default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
frame-system-rpc-runtime-api               = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
frame-try-runtime                          = { default-features = false, optional = true, git = "https://github.com/darwinia-network/substrate", branch = "main" }
pallet-authority-discovery                 = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
pallet-authorship                          = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
pallet-babe                                = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
pallet-bounties                            = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
pallet-collective                          = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
pallet-election-provider-multi-phase       = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
pallet-grandpa                             = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
pallet-identity                            = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
pallet-im-online                           = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
pallet-membership                          = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
pallet-multisig                            = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
pallet-offences                            = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
pallet-proxy                               = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
pallet-randomness-collective-flip          = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
pallet-recovery                            = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
pallet-scheduler                           = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
pallet-session                             = { default-features = false, features = ["historical"], git = "https://github.com/darwinia-network/substrate", branch = "main" }
pallet-society                             = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
pallet-sudo                                = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
pallet-timestamp                           = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
pallet-tips                                = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
pallet-transaction-payment                 = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
pallet-transaction-payment-rpc-runtime-api = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
pallet-treasury                            = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
pallet-utility                             = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
# paritytech primitives
sp-api                 = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
sp-authority-discovery = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
sp-block-builder       = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
sp-consensus-babe      = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
sp-core                = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
sp-inherents           = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
sp-npos-elections      = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
sp-offchain            = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
sp-runtime             = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
sp-session             = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
sp-staking             = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
sp-std                 = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
sp-transaction-pool    = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
sp-version             = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }

[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/darwinia-network/substrate", branch = "main" }

[features]
default = ["std"]

std = [
	# crates.io
	"codec/std",
	"serde",
	"serde_json",
	# darwinia-network frame
	"darwinia-balances/std",
	"darwinia-balances-rpc-runtime-api/std",
	"darwinia-crab-backing/std",
	"darwinia-democracy/std",
	"darwinia-elections-phragmen/std",
	"darwinia-ethereum-backing/std",
	"darwinia-ethereum-relay/std",
	"darwinia-header-mmr/std",
	"darwinia-header-mmr-rpc-runtime-api/std",
	"darwinia-relay-authorities/std",
	"darwinia-relay-primitives/std",
	"darwinia-relayer-game/std",
	"darwinia-staking/std",
	"darwinia-staking-rpc-runtime-api/std",
	"darwinia-support/std",
	"darwinia-tron-backing/std",
	"darwinia-vesting/std",
	# darwinia-network primitives
	"darwinia-primitives/std",
	"ethereum-primitives/std",
	# darwinia-network runtime
	"darwinia-runtime-common/std",
	# paritytech frame
	"frame-executive/std",
	"frame-support/std",
	"frame-system/std",
	"frame-system-rpc-runtime-api/std",
	"frame-try-runtime/std",
	"pallet-authorship/std",
	"pallet-authority-discovery/std",
	"pallet-babe/std",
	"pallet-bounties/std",
	"pallet-collective/std",
	"pallet-election-provider-multi-phase/std",
	"pallet-grandpa/std",
	"pallet-im-online/std",
	"pallet-identity/std",
	"pallet-membership/std",
	"pallet-multisig/std",
	"pallet-offences/std",
	"pallet-proxy/std",
	"pallet-randomness-collective-flip/std",
	"pallet-recovery/std",
	"pallet-scheduler/std",
	"pallet-session/std",
	"pallet-society/std",
	"pallet-sudo/std",
	"pallet-timestamp/std",
	"pallet-tips/std",
	"pallet-transaction-payment/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-treasury/std",
	"pallet-utility/std",
	# paritytech primitives
	"sp-api/std",
	"sp-authority-discovery/std",
	"sp-block-builder/std",
	"sp-consensus-babe/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-npos-elections/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-staking/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",
]

dev          = []
only-staking = []

try-runtime = [
	"frame-executive/try-runtime",
	"frame-try-runtime",
]

# A feature that should be enabled when the runtime should be build for on-chain
# deployment. This will disable stuff that shouldn't be part of the on-chain wasm
# to make it smaller like logging for example.
on-chain-release-build = [
	"sp-api/disable-logging",
]

runtime-benchmarks = [
	"frame-benchmarking",
	"frame-system-benchmarking",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-collective/runtime-benchmarks",
	"pallet-society/runtime-benchmarks",
]
