[package]
name = "darwinia-runtime-common"
version = "0.5.4"
authors = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia node runtime common"
edition = "2018"
license = "GPL-3.0"
homepage = "https://darwinia.network/"
repository = "https://github.com/darwinia-network/darwinia/"

[dependencies]
# crates
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false }
# substrate primitives
sp-runtime = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.darwinia.6" }
sp-std = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.darwinia.6" }
# darwinia primitives
darwinia-primitives = { default-features = false, path = "../../primitives" }
# substrate frame
frame-support = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.darwinia.6" }
frame-system = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.darwinia.6" }
pallet-authorship = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.darwinia.6" }
# darwinia frame
darwinia-balances = { default-features = false, git = "https://github.com/darwinia-network/darwinia-common.git", branch = "darwinia-master" }
darwinia-staking = { default-features = false, git = "https://github.com/darwinia-network/darwinia-common.git", branch = "darwinia-master" }
darwinia-support = { default-features = false, git = "https://github.com/darwinia-network/darwinia-common.git", branch = "darwinia-master" }

[features]
default = ["std"]
no_std = []
std = [
	# crates
	"codec/std",
	# substrate primitives
	"sp-runtime/std",
	"sp-std/std",
	# darwinia primitives
	"darwinia-primitives/std",
	# substrate frame
	"frame-support/std",
	"frame-system/std",
	"pallet-authorship/std",
	# darwinia frame
	"darwinia-balances/std",
	"darwinia-staking/std",
	"darwinia-support/std",
]
# TODO: benchmark
# runtime-benchmarks = []
