[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
build       = "build.rs"
description = "Darwinia Client Node"
edition     = "2018"
homepage    = "https://darwinia.network/"
license     = "GPL-3.0"
name        = "darwinia-cli"
repository  = "https://github.com/darwinia-network/darwinia/"
version     = "0.11.2"

	[package.metadata.wasm-pack.profile.release]
	# `wasm-opt` has some problems on linux, see
	# https://github.com/rustwasm/wasm-pack/issues/781 etc.
	wasm-opt = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# crates.io
log       = { version = "0.4.14" }
serde     = { version = "1.0.126", optional = true }
structopt = { version = "0.3.21" }
tokio     = { version = "0.3.7", optional = true, features = ["rt-multi-thread"] }
# darwinia-network service
darwinia-service = { default-features = false, path = "../node/service" }
# paritytech client
sc-cli          = { optional = true, git = "https://github.com/darwinia-network/substrate", branch = "main" }
sc-client-api   = { git = "https://github.com/darwinia-network/substrate", branch = "main" }
sc-executor     = { git = "https://github.com/darwinia-network/substrate", branch = "main" }
sc-network      = { optional = true, git = "https://github.com/darwinia-network/substrate", branch = "main" }
sc-service      = { git = "https://github.com/darwinia-network/substrate", branch = "main" }
sc-tracing      = { optional = true, git = "https://github.com/darwinia-network/substrate", branch = "main" }
try-runtime-cli = { optional = true, git = "https://github.com/darwinia-network/substrate", branch = "main" }
# paritytech frame
frame-benchmarking-cli = { optional = true, git = "https://github.com/darwinia-network/substrate", branch = "main" }
# paritytech primitives
sp-core = { git = "https://github.com/darwinia-network/substrate", branch = "main" }
# this crate is used only to enable `trie-memory-tracker` feature
# see https://github.com/paritytech/substrate/pull/6745
sp-trie = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/darwinia-network/substrate", branch = "main" }
try-runtime-cli              = { optional = true, git = "https://github.com/darwinia-network/substrate", branch = "main" }

[features]
default = [
	"cli",
	"db",
]

cli = [
	"serde",
	"tokio",
	"sc-cli",
	"sc-network",
	"sc-tracing",
	"darwinia-service/full-node",
]
db = ["darwinia-service/db"]

trie-memory-tracker = ["sp-trie/memory-tracker"]
wasmtime = [
	"sc-cli/wasmtime",
	"trie-memory-tracker",
]

dev = ["darwinia-service/dev"]

try-runtime = [
	"darwinia-service/try-runtime",
	"try-runtime-cli",
]

runtime-benchmarks = [
	"frame-benchmarking-cli",
	"darwinia-service/runtime-benchmarks",
]
