[package]
name = "darwinia-cli"
version = "0.6.1"
authors = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia Client Node"
edition = "2018"
license = "GPL-3.0"
homepage = "https://darwinia.network/"
repository = "https://github.com/darwinia-network/darwinia/"
build = "build.rs"

[package.metadata.wasm-pack.profile.release]
# `wasm-opt` has some problems on linux, see
# https://github.com/rustwasm/wasm-pack/issues/781 etc.
wasm-opt = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# crates
log = { version = "0.4.8" }
serde = { version = "1.0.106", optional = true }
structopt = { version = "0.3.13" }
tokio = { version = "0.2.18", features = ["rt-threaded"], optional = true }
toml = { version = "0.5.6", optional = true }
wasm-bindgen = { version = "0.2.60", optional = true }
wasm-bindgen-futures = { version = "0.4.10", optional = true }
# substrate frame
# TODO: benchmark
# frame-benchmarking-cli = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-rc.darwinia.1", optional = true }
# substrate client
sc-cli = { optional = true, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-rc.darwinia.1" }
sc-client-api = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-rc.darwinia.1" }
sc-executor = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-rc.darwinia.1" }
sc-network = { optional = true, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-rc.darwinia.1" }
sc-service = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-rc.darwinia.1" }
sc-tracing = { optional = true, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-rc.darwinia.1" }
# substrate utils
substrate-browser-utils = { optional = true, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-rc.darwinia.1" }
# darwinia service
darwinia-service = { default-features = false, path = "../service" }

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-rc.darwinia.1" }

[features]
default = [
	"wasmtime",
	"db",
	"cli",
]
wasmtime = ["sc-cli/wasmtime"]
db = ["darwinia-service/db"]
cli = [
	"serde",
	"tokio",
	"toml",
	"sc-cli",
	"sc-network",
	"sc-tracing",
	# TODO: benchmark
	# "frame-benchmarking-cli",
	"darwinia-service/full-node",
]
browser = [
	"wasm-bindgen",
	"wasm-bindgen-futures",
	"substrate-browser-utils",
]
# TODO: benchmark
# runtime-benchmarks = ["service/runtime-benchmarks"]
