[package]
name = "darwinia-kton"
version = "0.1.0"
authors = ["Darwinia Network <hello@itering.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.101", optional = true }
safe-mix = { version = "1.0.0", default-features = false }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
substrate-keyring = { git = 'https://github.com/darwinia-network/substrate.git', optional = true }
rstd = { package = "sr-std", git = 'https://github.com/darwinia-network/substrate.git', default-features = false }
sr-primitives = { git = 'https://github.com/darwinia-network/substrate.git', default-features = false }
srml-support = { git = 'https://github.com/darwinia-network/substrate.git', default-features = false }
system = { package = "srml-system", git = 'https://github.com/darwinia-network/substrate.git', default-features = false }
timestamp = { package = "srml-timestamp", git = 'https://github.com/darwinia-network/substrate.git', default-features = false }
substrate-primitives = { git = 'https://github.com/darwinia-network/substrate.git', default-features = false }

darwinia-support = { path = "../support", default-features = false }

[dev-dependencies]
runtime_io = { package = "sr-io", git = 'https://github.com/darwinia-network/substrate.git' }
substrate-primitives = { git = 'https://github.com/darwinia-network/substrate.git' }

[features]
default = ["std"]
std = [
	"serde",
	"safe-mix/std",
	"codec/std",
	"substrate-keyring",
	"rstd/std",
	"srml-support/std",
	"sr-primitives/std",
	"system/std",
	"timestamp/std",
	"substrate-primitives/std",

	"darwinia-support/std",
]
