[package]
name = "darwinia-support"
version = "0.5.0"
authors = ["darwinia <hello@darwinia.network>"]
edition = "2018"
license = "GPL-3.0"
homepage = "https://darwinia.network/"
repository = "https://github.com/darwinia-network/darwinia/"
description = "Support code for Darwinia runtime."

[dependencies]
# crates.io
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
num-traits = { version = "0.2.8", default-features = false }

# github.com
frame-support = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.3" }
sp-runtime = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.3" }
sp-std = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.3" }

[features]
default = ["std"]
std = [
	"codec/std",
	"num-traits/std",

	"frame-support/std",
	"sp-runtime/std",
	"sp-std/std",
]