title = "Darwinia Node Runtime Types"

[staking]
	[staking.basic]
	RingBalance = "Balance"
	KtonBalance = "Balance"
	MomentT = "Moment"
	Power = "u32"
	DepositId = "U256"

	[staking.complex]
	StakingBalanceT = "StakingBalance"
	StakingBalance._enum.All = ""
	StakingBalance._enum.RingBalance = "Balance"
	StakingBalance._enum.KtonBalance = "Balance"

	StakingLedgerT = "StakingLedger"
	StakingLedger.stash = "AccountId"
	StakingLedger.active_ring = "Compact<Balance>"
	StakingLedger.active_deposit_ring = "Compact<Balance>"
	StakingLedger.active_kton = "Compact<Balance>"
	StakingLedger.deposit_items = "Vec<TimeDepositItem>"
	StakingLedger.ring_staking_lock = "StakingLock"
	StakingLedger.kton_staking_lock = "StakingLock"

	TimeDepositItem.value = "Compact<Balance>"
	TimeDepositItem.start_time = "Compact<Moment>"
	TimeDepositItem.expire_time = "Compact<Moment>"
	
	Exposure.own_ring_balance = "Compact<Balance>"
	Exposure.own_kton_balance = "Compact<Balance>"
	Exposure.own_power = "Power"
	Exposure.total_power = "Power"
	Exposure.others = "Vec<IndividualExposure>"
	
	IndividualExposure.who = "AccountId"
	IndividualExposure.ring_balance = "Compact<Balance>"
	IndividualExposure.kton_balance = "Compact<Balance>"
	IndividualExposure.power = "Power"

	ValidatorReward.who = "AccountId"
	ValidatorReward.amount = "Compact<Balance>"
	ValidatorReward.nominators_reward = "Vec<NominatorReward>"

	NominatorReward.who = "AccountId"
	NominatorReward.amount = "Compact<Balance>"

RKT = "RK"
	RK.r = "Balance"
	RK.k = "Balance"

[support]
	[support.complex]
	BalanceLock.id = "LockIdentifier"
	BalanceLock.lock_for = "LockFor"
	BalanceLock.lock_reasons = "LockReasons"

	LockFor._enum.Common = "Common"
	LockFor._enum.Staking = "StakingLock"

	Common.amount = "Balance"

	StakingLock.staking_amount = "Balance"
	StakingLock.unbondings = "Vec<Unbonding>"

	Unbonding.amount = "Balance"
	Unbonding.moment = "BlockNumber"

	LockReasons._enum.Fee = ""
	LockReasons._enum.Misc = ""
	LockReasons._enum.All = ""

[eth]
	[eth.basic]
	EthBlockNumber = "u64"
	EthAddress = "H160"

	[eth.complex]
	EthTransactionIndex = "(H256, u64)"

	HeaderInfo.total_difficulty = "U256"
	HeaderInfo.parent_hash = "H256"
	HeaderInfo.number = "EthBlockNumber"

	EthHeader.parent_hash = "H256"
	EthHeader.timestamp = "u64"
	EthHeader.number = "EthBlockNumber"
	EthHeader.auth = "EthAddress"
	EthHeader.transaction_root = "H256"
	EthHeader.uncles_hash = "H256"
	EthHeader.extra_data = "Bytes"
	EthHeader.state_root = "H256"
	EthHeader.receipts_root = "H256"
	EthHeader.log_bloom = "Bloom"
	EthHeader.gas_used = "U256"
	EthHeader.gas_limit = "U256"
	EthHeader.difficulty = "U256"
	EthHeader.seal = "Vec<Bytes>"
	EthHeader.hash = "Option<H256>"

	Bloom._struct = "[u8; 256]"

	Receipt.gas_used = "U256"
	Receipt.log_bloom = "Bloom"
	Receipt.logs = "Vec<LogEntry>"
	Receipt.outcome = "TransactionOutcome"
	
	EthReceiptProof.index = "u64"
	EthReceiptProof.proof = "Bytes"
	EthReceiptProof.header_hash = "H256"