[package]
name = "darwinia-eth-relay"
version = "0.2.0"
authors = ["Darwinia Network <hello@darwinia.network>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.101", optional = true }

codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
rstd = { package = "sr-std", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
system = { package = "srml-system",  git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
sr-primitives = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
support = { package = "srml-support", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
sr-eth-primitives = { path = "../../core/sr-eth-primitives", default-features = false }

rlp = { package = "rlp", git = "https://github.com/darwinia-network/parity-common.git", default-features = false}
ethash = { git = "https://github.com/hammeWang/ethash-rs.git", rev = "70a4f078", default-features = false}
merkle-patricia-trie = { path = "../../core/merkle-patricia-trie", default-features = false}

[dev-dependencies]
runtime-io = { package = "sr-io", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop"}
primitives = { package = "substrate-primitives",  git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
transaction-payment = { package = "srml-transaction-payment", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
rustc-hex = "2.0"
keccak-hasher = "0.15.2"
triehash = { package = "triehash", git = "https://github.com/darwinia-network/parity-common.git" }
hex-literal = "0.2.1"

[features]
default = ["std"]
std = [
    "serde/std",
	"codec/std",
    "rstd/std",
    "sr-primitives/std",
    "support/std",
    "system/std",
    "sr-eth-primitives/std",
    "ethash/std",
    "rlp/std",
    "ethash/std",
    "merkle-patricia-trie/std",
]
