[package]
name = "darwinia-chainrelay"
version = "0.1.0"
authors = ["hammeWang <dsw0602@foxmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
rstd = { package = "sr-std", git = 'https://github.com/paritytech/substrate.git', default-features = false }
support = { package = "srml-support", git = 'https://github.com/paritytech/substrate.git', default-features = false }
system = { package = "srml-system",  git = 'https://github.com/paritytech/substrate.git', default-features = false }

merkle-mountain-range = { path = "../../core/merkle-mountain-range", default-features = false }

[features]
default = ["std"]
std = [
    "rstd/std",
    "support/std",
    "system/std",

    "merkle-mountain-range/std",
]
