[package]
name = "darwinia-eth-backing"
version = "0.1.0"
authors = ["Darwinia Network <hello@darwinia.network>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.101", optional = true }

codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
rstd = { package = "sr-std", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
support = { package = "srml-support", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
system = { package = "srml-system",  git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
timestamp = { package = "srml-timestamp", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
darwinia-support = { package = "darwinia-support", path = "../support", default-features = false }
darwinia-eth-relay = { package = "darwinia-eth-relay", path = "../eth-relay", default-features = false }
sr-eth-primitives = { path = "../../core/sr-eth-primitives", default-features = false }

sr-primitives = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
hex-literal = "0.2.1"

[features]
default = ["std"]
std = [
    "serde/std",

	"codec/std",
    "rstd/std",
    "support/std",
    "system/std",
    "timestamp/std",
    "darwinia-support/std",
    "darwinia-eth-relay/std",
    "sr-eth-primitives/std",
    "sr-primitives/std",
]
