[package]
name = "merkle-patricia-trie"
version = "0.4.0"
authors = ["Darwinia Network <hello@darwinia.network>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# crates.io
hashbrown = { version = "0.6.0" }

# github.com
hash = { package = "keccak-hash", default-features = false, git = "https://github.com/darwinia-network/parity-common.git" }
rlp = { default-features = false, git = "https://github.com/darwinia-network/parity-common.git" }
sp-std = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }

[dev-dependencies]
criterion = "0.2.10"
ethereum-types = "0.5.2"
hex = "0.3.2"
rand = "0.6.3"
uuid = { version = "0.7", features = ["serde", "v4"] }

[features]
default = ["std"]
std = [
	"hash/std",
	"rlp/std",
]

[[bench]]
name = "trie"
harness = false
