[package]
name = "darwinia-eth-backing"
version = "0.5.0"
authors = ["Darwinia Network <hello@darwinia.network>"]
edition = "2018"
license = "GPL-3.0"
homepage = "https://darwinia.network/"
repository = "https://github.com/darwinia-network/darwinia/"
description = "FRAME pallet to backing Ethereum assets"

[dependencies]
# crates.io
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.101", optional = true }

# github.com
ethabi = { default-features = false, git = "https://github.com/darwinia-network/ethabi.git", branch = "with_no_std" }

frame-support = { default-features = false , git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.3" }
frame-system = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.3" }

sp-core = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.3" }
sp-runtime = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.3" }
sp-std = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.3" }

# darwinia
darwinia-eth-relay = { default-features = false, path = "../relay" }
darwinia-support = { default-features = false, path = "../../../support" }

eth-primitives = { default-features = false, path = "../../../../primitives/eth-primitives" }

[dev-dependencies]
hex-literal = "0.2.1"
rustc-hex = "2.0"

rlp = { package = "rlp", git = "https://github.com/darwinia-network/parity-common.git" }

pallet-session = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.3"}

sp-io = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.3" }
sp-phragmen = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.3"}
sp-staking = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.3"}

kton = { package = "darwinia-kton", path = "../../../balances/kton" }
ring = { package = "darwinia-ring", path = '../../../balances/ring' }
staking = { package = "darwinia-staking", path = "../../../staking" }

[features]
default = ["std"]
std = [
	"codec/std",
	"serde/std",

	"ethabi/std",
	"frame-support/std",
	"frame-system/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",

	"darwinia-support/std",
	"darwinia-eth-relay/std",

	"eth-primitives/std",
]
