[package]
name = "node-executor"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate node implementation in Rust."
edition = "2018"

[dependencies]
trie-root = "0.15.2"
codec = { package = "parity-scale-codec", version = "1.0.0" }
runtime_io = { package = "sr-io", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
state_machine = { package = "substrate-state-machine", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
substrate-executor = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
primitives = { package = "substrate-primitives", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
trie = { package = "substrate-trie", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }

node-primitives = { path = "../primitives" }
node-runtime = { path = "../runtime" }

[dev-dependencies]
test-client = { package = "substrate-test-client", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
keyring = { package = "substrate-keyring", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
runtime_primitives = { package = "sr-primitives", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
runtime_support = { package = "srml-support", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
session = { package = "srml-session", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
staking = { package = "darwinia-staking", path = '../../srml/staking' }
system = { package = "srml-system", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
timestamp = { package = "srml-timestamp", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
treasury = { package = "srml-treasury", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop"  }
contracts = { package = "srml-contracts", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
grandpa = { package = "srml-grandpa", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
indices = { package = "srml-indices", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
wabt = "0.9.2"

balances = { package = "darwinia-balances", path = '../../srml/balances', default-features = false }

[features]
benchmarks = []
