[package]
name = "node-executor"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate node implementation in Rust."
edition = "2018"

[dependencies]
substrate-executor = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }

node-runtime = { path = "../runtime" }


[features]
wasmtime = [
    "substrate-executor/wasmtime",
]
