name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: itering/actions
          path: .github/actions
          persist-credentials: false
          ssh-key: "${{ secrets.ITERING_ACTIONS_DEPLOY_KEY }}"

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2020-09-20
          override: true
          target: wasm32-unknown-unknown

    #   - uses: actions/cache@v2
    #     with:
    #       path: |
    #         ~/.cargo/registry
    #         ~/.cargo/git
    #         target
    #       key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    #       restore-keys: |
    #         ${{ runner.os }}-cargo-

      - name: Overall test
        run: cargo test

      - uses: ./.github/actions/dingtalk-notify
        if: failure() && (github.event_name == 'pull_request' && github.event.pull_request.draft == false || github.event_name != 'pull_request')
        with:
          dingtalk_bot_token: ${{ secrets.DINGTALK_BOT_TOKEN }}
