[package]
name = "offbridge"
version = "0.1.0"
authors = ["hammeWang <dsw0602@foxmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.101", optional = true }
safe-mix = { version = "1.0.0", default-features = false }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
rstd = { package = "sr-std", git = 'https://github.com/paritytech/substrate.git', default-features = false }
srml-support = { git = 'https://github.com/paritytech/substrate.git', default-features = false }
system = { package = "srml-system", git = 'https://github.com/paritytech/substrate.git', default-features = false }
runtime-io = { package = "sr-io", git = 'https://github.com/paritytech/substrate.git', default-features = false }
sr-primitives = { git = 'https://github.com/paritytech/substrate.git', default-features = false }
app-crypto = { package = "substrate-application-crypto", git = "https://github.com/paritytech/substrate.git", default-features = false }
offchain-primitives = { package = "substrate-offchain-primitives", git = "https://github.com/paritytech/substrate.git", default-features = false }

[dev-dependencies]
primitives = { package = "substrate-primitives", git = "https://github.com/paritytech/substrate.git" }

[features]
default = ["std"]
std = [
    "serde",
    "safe-mix/std",
    "codec/std",
    "rstd/std",
    "srml-support/std",
    "system/std",
    "runtime-io/std",
    "sr-primitives/std",
    "app-crypto/std",
    "offchain-primitives/std",
]

