[package]
name = "darwinia-treasury"
version = "2.0.0"
authors = ["darwinia <hello@darwinia.network>"]
edition = "2018"

[dependencies]
# crates.io
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.101", optional = true, features = ["derive"] }

# github.com
frame-support = { version = "2.0.0", default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
frame-system = { version = "2.0.0", default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
sp-std = { version = "2.0.0", default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
sp-runtime = { version = "2.0.0", default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }

darwinia-support = { default-features = false, path = "../support" }

[dev-dependencies]
sp-core = { version = "2.0.0", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
sp-io ={ version = "2.0.0", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }

darwinia-ring = { path = "../balances/ring" }
darwinia-kton = { path = "../balances/kton" }

[features]
default = ["std"]
std = [
	"codec/std",
	"serde",

	"frame-support/std",
	"frame-system/std",
	"sp-std/std",
	"sp-runtime/std",

	"darwinia-support/std",
]
