[package]
name = "darwinia-treasury"
version = "0.5.0"
authors = ["Darwinia Network <hello@darwinia.network>"]
edition = "2018"
license = "GPL-3.0"
homepage = "https://darwinia.network/"
repository = "https://github.com/darwinia-network/darwinia/"
description = "FRAME pallet to manage treasury"

[dependencies]
# crates.io
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.101", optional = true, features = ["derive"] }

# github.com
frame-support = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.3" }
frame-system = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.3" }

sp-std = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.3" }
sp-runtime = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.3" }

# darwinia
darwinia-support = { default-features = false, path = "../support" }

[dev-dependencies]
sp-core = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.3" }
sp-io ={ git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.3" }

pallet-kton = { package = "darwinia-kton", path = "../balances/kton" }
pallet-ring = { package = "darwinia-ring", path = "../balances/ring" }

[features]
default = ["std"]
std = [
	"codec/std",
	"serde",

	"frame-support/std",
	"frame-system/std",

	"sp-std/std",
	"sp-runtime/std",

	"darwinia-support/std",
]
